import Chocolate from './download.jpg';

export const chocolates = [
  {
    id: 1,
    photo: Chocolate,
    chocolateName: 'Dark chocolate',
    price: 100,
    pricePerUnit: 6.66,
    count: 15,
    category: 'normal',
  },
  {
    id: 2,
    photo: Chocolate,
    chocolateName: 'Milk chocolate',
    price: 120,
    pricePerUnit: 8,
    count: 15,
    category: 'normal',
  },
  {
    id: 3,
    photo: Chocolate,
    chocolateName: 'White chocolate',
    price: 130,
    pricePerUnit: 8.66,
    count: 15,
    category: 'normal',
  },
  {
    id: 4,
    photo: Chocolate,
    chocolateName: 'Dark dry fruit chocolate',
    price: 120,
    pricePerUnit: 8,
    count: 15,
    category: 'dryFruit',
  },
  {
    id: 5,
    photo: Chocolate,
    chocolateName: 'Milk dry fruit chocolate',
    price: 140,
    pricePerUnit: 9.33,
    count: 15,
    category: 'dryFruit',
  },
  {
    id: 6,
    photo: Chocolate,
    chocolateName: 'White dry fruit chocolate',
    price: 150,
    pricePerUnit: 10,
    count: 15,
    category: 'dryFruit',
  },
  {
    id: 7,
    photo: Chocolate,
    chocolateName: 'Dry fruit bar',
    price: 120,
    pricePerUnit: 10,
    count: 2,
    category: 'dryFruit',
  },
  {
    id: 8,
    photo: Chocolate,
    chocolateName: 'Plain chocolate bar',
    price: 100,
    pricePerUnit: 50,
    count: 2,
    category: 'special',
  },
  {
    id: 9,
    photo: Chocolate,
    chocolateName: 'Snickers date chocolate',
    price: 150,
    pricePerUnit: 75,
    count: 2,
    category: 'special',
  },
  {
    id: 10,
    photo: Chocolate,
    chocolateName: 'White chocolate cake balls',
    price: 30,
    pricePerUnit: 30,
    count: 1,
    category: 'special',
  },
  {
    id: 11,
    photo: Chocolate,
    chocolateName: 'Cake balls',
    price: 30,
    pricePerUnit: 30,
    count: 1,
    category: 'special',
  },
];
